---
Name: swiftypesearch
---
SiteConfig:
  extensions:
    - SwiftypeSearchSiteConfig
LeftAndMain:
  extensions:
    - Marcz\Swiftype\SwiftypeAdminExtension
Marcz\Search\Config:
  clients:
    - name: 'Swiftype'
      write: true
      delete: true
      export: 'json'
      class: 'Marcz\Swiftype\SwiftypeClient'
  indices:
    - name: 'FAQ'
      class: 'FAQ'
      has_one: true
      has_many: true
      many_many: true
      searchableAttributes:
        - 'Question'
        - 'Answer'
        - 'Keywords'
        - 'Category'
      attributesForFaceting:
        - 'Keywords'
        - 'Category'
Marcz\Search\Processor\Exporter:
  extensions:
    - Marcz\Swiftype\Extensions\Exporter
